services:
  - type: web
    name: zoro-md
    env: node
    branch: main
    repo: https://github.com/zokosir/ZORO-MD-V1.0.1
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: zoro-md;https://i.imgur.com/0Eka4Gs.jpeg
      - key: WARN_COUNT
        value: 3
      - key: AUTO_STATUS_VIEWS
        value: false
      - key: MEDIA_DATA
        value: ʟɪꜱᴛ ᴍᴇɴᴜ;zoro-md;https://i.imgur.com/0Eka4Gs.jpeg
      - key: HANDLER
        value: /
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: STICKER_PACKNAME
        value: zoro-md
      - key: AUDIO_DATA
        value:zoro-md;https://i.imgur.com/0Eka4Gs.jpeg
      - key: SUDO
        value: 919778158839
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
